version: '3.9'

volumes:
  postgres-data:


services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data


  tron_scanner:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tron_scanner
    restart: always
    command: /start.sh
    depends_on:
      - db
    env_file:
      - .env

